SHOW TABLES IN SCHEMA ATMOSYNC_DB.RAW;

SELECT COUNT(*) FROM ATMOSYNC_DB.RAW.FACT_SPOILAGE_ARBITRAGE;

ALTER TABLE ATMOSYNC_DB.RAW.FACT_SPOILAGE_ARBITRAGE CLUSTER BY(DESTINATION,SPOILAGE_RISK);

SHOW TABLES LIKE 'FACT_SPOILAGE_ARBITRAGE' IN SCHEMA ATMOSYNC_DB.RAW;

SELECT * FROM ATMOSYNC_DB.RAW.FACT_SPOILAGE_ARBITRAGE WHERE DESTINATION ='Kochi' AND SPOILAGE_RISK='High';