CREATE OR REPLACE VIEW RAW.VW_HIGH_RISK_CONTAINERS AS
SELECT
    CONTAINER_ID,
    COMMODITY,
    DESTINATION,
    MARKET_PRICE_USD_PER_TON,
    SPOILAGE_RISK,
    PRIORITY_LEVEL,
    ESTIMATED_TIME_TO_SPOIL_HOURS,
    ESTIMATED_TRAVEL_TIME_HOURS,
    SPOILAGE_MARGIN_HOURS,
    SHIPMENT_STATUS,
    REROUTE_RECOMMENDED
FROM RAW.FACT_SPOILAGE_ARBITRAGE
WHERE SHIPMENT_STATUS = 'Spoilage Expected' AND PRIORITY_LEVEL='Critical'

SELECT * FROM RAW.VW_HIGH_RISK_CONTAINERS;

