CREATE WAREHOUSE ATMOSYNC_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE ATMOSYNC_WH;

CREATE DATABASE ATMOSYNC_DB;
USE DATABASE ATMOSYNC_DB;

CREATE SCHEMA RAW;

CREATE SCHEMA STAGING;

CREATE SCHEMA ANALYTICS;

SHOW WAREHOUSES;

SHOW DATABASES;

SHOW SCHEMAS;

USE SCHEMA RAW;

CREATE OR REPLACE TABLE IOT_SENSOR_DATA
(
    TIMESTAMP TIMESTAMP_NTZ,
    CONTAINER_ID STRING,
    COMMODITY STRING,
    TEMPERATURE_C FLOAT,
    HUMIDITY_PERCENT FLOAT,
    VIBRATION_G FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    DESTINATION STRING,
    MARKET_PRICE_USD_PER_TON NUMBER,
    SPOILAGE_RISK STRING,
    RECOMMENDED_ACTION STRING
);

DESC TABLE RAW.IOT_SENSOR_DATA;
