from kafka import KafkaProducer
import pandas as pd
import json
import time

# Create Kafka Producer
producer = KafkaProducer(
    bootstrap_servers='localhost:9092',
    value_serializer=lambda v: json.dumps(v).encode('utf-8')
)

# Read CSV file generated by simulator
df = pd.read_csv("iot_sensor_data.csv")

print("Sending Sensor Data to Kafka...\n")

# Send each row to Kafka
for index, row in df.iterrows():

    message = row.to_dict()

    producer.send("sensor-data", value=message)

    print(f"Sent : {message}")

    # Wait 1 second to simulate live sensor data
    time.sleep(1)

producer.flush()

print("\nAll Sensor Data Sent Successfully!")

